import { environment } from "@raycast/api";
import { execFileSync } from "child_process";
import { chmodSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";
import { ensureHelper } from "./native";

/**
 * Optional background watcher for precise switch timing.
 *
 * A launchd agent runs a tiny loop that polls the active space (via the same
 * SkyLight helper) roughly once a second and appends a timestamped event on
 * every change. The tracker folds these exact timestamps into the session, so
 * per-space totals stay precise even though Raycast only redraws the menu bar
 * on its own (slower) refresh cadence.
 */

export const WATCHER_LABEL = "com.raycast.space-time-tracker.watcher";
const POLL_SECONDS = 1;

export interface SwitchEvent {
  /** epoch milliseconds */
  t: number;
  /** macOS space id */
  id: number;
}

function eventsFile(): string {
  return join(environment.supportPath, "space-events.jsonl");
}

function watcherScript(): string {
  return join(environment.supportPath, "space-watcher.sh");
}

function plistPath(): string {
  return join(homedir(), "Library", "LaunchAgents", `${WATCHER_LABEL}.plist`);
}

function uid(): number {
  return typeof process.getuid === "function" ? process.getuid() : 501;
}

function writeWatcherScript(helper: string): string {
  const events = eventsFile();
  const script = `#!/bin/sh
# Auto-generated by the Spacetime Raycast extension.
HELPER="${helper}"
EVENTS="${events}"
LAST=""
while true; do
  ID=$("$HELPER" 2>/dev/null)
  if [ -n "$ID" ] && [ "$ID" != "0" ] && [ "$ID" != "$LAST" ]; then
    T=$(/usr/bin/perl -MTime::HiRes=time -e 'printf("%d", time()*1000)' 2>/dev/null)
    [ -z "$T" ] && T=$(( $(date +%s) * 1000 ))
    printf '{"t":%s,"id":%s}\\n' "$T" "$ID" >> "$EVENTS"
    LAST="$ID"
  fi
  sleep ${POLL_SECONDS}
done
`;
  const path = watcherScript();
  writeFileSync(path, script, { mode: 0o755 });
  chmodSync(path, 0o755);
  return path;
}

function writePlist(script: string): string {
  const sup = environment.supportPath;
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${WATCHER_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${script}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>${join(sup, "watcher.out.log")}</string>
  <key>StandardErrorPath</key>
  <string>${join(sup, "watcher.err.log")}</string>
</dict>
</plist>
`;
  const path = plistPath();
  mkdirSync(join(homedir(), "Library", "LaunchAgents"), { recursive: true });
  writeFileSync(path, plist, "utf8");
  return path;
}

/** Installs and starts the launchd watcher agent. Idempotent. */
export function installWatcher(): void {
  mkdirSync(environment.supportPath, { recursive: true });
  const helper = ensureHelper();
  const script = writeWatcherScript(helper);
  const plist = writePlist(script);
  const target = `gui/${uid()}`;

  // Replace any existing instance.
  try {
    execFileSync("/bin/launchctl", ["bootout", `${target}/${WATCHER_LABEL}`], { stdio: "ignore" });
  } catch {
    // not loaded — fine
  }
  execFileSync("/bin/launchctl", ["bootstrap", target, plist], { timeout: 5000 });
  try {
    execFileSync("/bin/launchctl", ["kickstart", "-k", `${target}/${WATCHER_LABEL}`], { stdio: "ignore" });
  } catch {
    // kickstart best-effort
  }
}

/** Stops and removes the launchd watcher agent. */
export function uninstallWatcher(): void {
  try {
    execFileSync("/bin/launchctl", ["bootout", `gui/${uid()}/${WATCHER_LABEL}`], { stdio: "ignore" });
  } catch {
    // not loaded — fine
  }
  try {
    if (existsSync(plistPath())) rmSync(plistPath());
  } catch {
    // ignore
  }
}

/** True when the launchd watcher agent is loaded. */
export function isWatcherRunning(): boolean {
  try {
    execFileSync("/bin/launchctl", ["print", `gui/${uid()}/${WATCHER_LABEL}`], {
      stdio: "ignore",
      timeout: 4000,
    });
    return true;
  } catch {
    return false;
  }
}

/** Reads and clears all pending switch events, sorted by time. */
export function consumeEvents(): SwitchEvent[] {
  const file = eventsFile();
  if (!existsSync(file)) return [];
  let raw = "";
  try {
    raw = readFileSync(file, "utf8");
  } catch {
    return [];
  }
  clearEvents();
  const events: SwitchEvent[] = [];
  for (const line of raw.split("\n")) {
    const s = line.trim();
    if (!s) continue;
    try {
      const obj = JSON.parse(s) as { t: number; id: number };
      if (typeof obj.t === "number" && typeof obj.id === "number") events.push({ t: obj.t, id: obj.id });
    } catch {
      // skip malformed line
    }
  }
  events.sort((a, b) => a.t - b.t);
  return events;
}

export function clearEvents(): void {
  try {
    writeFileSync(eventsFile(), "");
  } catch {
    // ignore
  }
}
